# Generated by Django 4.0.4 on 2022-04-17 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0003_alter_document_date_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Année_gestion',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Date_contact',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Date_depot',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Date_envoie',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Date_gestion',
        ),
        migrations.RemoveField(
            model_name='document',
            name='Date_retour',
        ),
        migrations.AlterField(
            model_name='document',
            name='Clé_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cdc_Documents.typedocument'),
        ),
    ]
