# Generated by Django 4.0.4 on 2022-05-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0005_rename_clé_type_document_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedocument',
            old_name='nbre_pièces',
            new_name='nbre_pieces',
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='typedocument',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
