# Generated by Django 4.0.4 on 2022-05-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0006_rename_nbre_pièces_typedocument_nbre_pieces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Cdc_Documents.typedocument'),
        ),
    ]
