# Generated by Django 4.0.4 on 2022-05-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0007_alter_document_id_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='réf',
            new_name='ref',
        ),
    ]
