# Generated by Django 4.0.4 on 2022-05-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0010_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ref',
            field=models.CharField(max_length=10),
        ),
    ]
