# Generated by Django 4.0.4 on 2022-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0011_alter_document_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=50)),
                ('type_admin', models.CharField(max_length=50)),
            ],
        ),
    ]
