# Generated by Django 4.0.4 on 2022-05-25 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0013_rename_nom_admin_administration_nom_administration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='nom_administration',
            new_name='nom_admin',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='type_administration',
            new_name='type_admin',
        ),
    ]
