# Generated by Django 4.0.4 on 2022-06-03 09:22

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0014_rename_nom_administration_administration_nom_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='Année_gestion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='document',
            name='Date_depot',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
