# Generated by Django 4.0.4 on 2022-06-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0018_alter_document_id_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='id_service',
        ),
    ]
