# Generated by Django 4.0.4 on 2022-06-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0019_remove_document_id_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id_serv',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='Cdc_Documents.service'),
        ),
    ]
