# Generated by Django 4.0.4 on 2022-06-04 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0024_alter_document_id_serv'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='id_admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='administration', to='Cdc_Documents.administration'),
        ),
    ]
