# Generated by Django 4.0.4 on 2022-08-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cdc_Documents', '0025_document_id_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauOrdre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_Bureau', models.CharField(max_length=50)),
                ('num_Bureau', models.IntegerField()),
            ],
        ),
    ]
